# Generated by Django 3.2.12 on 2022-03-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data atualização')),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data atualização')),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuário')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('comentario', models.TextField(blank=True, default='', verbose_name='Comentário')),
                ('avaliacao', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Avaliação')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='core.curso')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(fields=('email', 'curso'), name='unique email e curso'),
        ),
    ]
